### ISSUE TITLE
[HELP] Sub path Hosting not working + Host URL gets modified ?

### ISSUE THREAD

**Issue by AmansRevenger** [Wizarrrr/wizarr#120]
**Describe the bug**
I cant get a subpath reverse proxy setup with SWAG to work + the URL for my server gets bugged in the Invitiation creation process

I tried two different configs for wizarr.subfolder.conf

```
location ^~ /wizarr/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream_app wizarr;
        set $upstream_port 5690;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	}
```
Gets 502, 

```
	location ^~ /wizarr/ {

    proxy_pass 					http://192.168.1.XXX:5690/;
    proxy_set_header 			X-Real-IP 			$remote_addr;
    proxy_set_header 			X-Forwarded-Host 	$server_name;
    proxy_set_header 			X-Forwarded-Proto 	$scheme;
    proxy_set_header 			X-Forwarded-For 	$proxy_add_x_forwarded_for;
    proxy_set_header 			X-Forwarded-Ssl on;
    proxy_set_header                        Host                $http_host;
	}	



```
gets 404 because it tries to redirect to domain.noip.me/admin instantly (no subpath support apparently)

**Screenshots**
![image](https://user-images.githubusercontent.com/18306225/235442466-e232bead-b3c8-46c1-898a-86178d9c7b77.png)

So it correctly finds my server under https://<MYDOMAIN>.noip.me

![image](https://user-images.githubusercontent.com/18306225/235442558-43bd9c1e-5884-491b-98ee-b970e08df96d.png)
I can create Invitiations locally just fine, BUT

![image](https://user-images.githubusercontent.com/18306225/235442708-5fff7fec-26f7-48ac-998e-a10ae18996ec.png)

it makes subdomain.noip.me to subdomain.nop.me without the i in ip. ???

**Logs**
If applicable, add logs to help explain your problem
```
2023/05/01 12:41:36 [error] 643#643: *1 wizarr could not be resolved (3: Host not found), client: <docker-internal.ip>, server: subdomain.noip.me, request: "GET /wizarr/j/<inviteToken> HTTP/2.0", host: "subdomain.noip.me"

```

**Additional context**
If it doesnt support subpath, just put it somewhere in the documentation...

**Comment by mtthidoteu** [comment]
Hi, have you managed to make it this work?

**Comment by AmansRevenger** [comment]
Hi

No i havent, and havent tried without an update since the issue is clearly not on my side

**Comment by mtthidoteu** [comment]
> Hi
> 
> No i havent, and havent tried without an update since the issue is clearly not on my side

Right from I've seen, it looks like you've just made a typo in the APP_URL environment variable :)

**Comment by oddsoul** [comment]
I have a similar issue with Nginx Proxy Manager where it refuses to scan libraries due to URL or token issue..

**Comment by phobiac** [comment]
I ran into this issue today and after much digging I suspect this would require code changes to Wizarr in order to work but I am not familiar enough with the project to make them.

To explain, the exact scenario I have is trying to have Wizarr accessible under a subpath, as in `subdomain.mysite.com/wizarr`. I am using nginx and hosting Wizarr in Unraid. My nginx block is fairly simple:
````
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name subdomain.mysite.com;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location /wizarr/ {
        include /config/nginx/proxy.conf;
        proxy_pass http://wizarr.local:5690/;
    }

}
````
I also set the APP_URL environment variable to `https://subdomain.mysite.com/wizarr/`

Wizarr loads perfectly fine at the local address, and it is sort of accessible at `subdomain.mysite.com/wizarr/` but what happens is I am immediately redirected to `subdomain.mysite.com/admin/` upon loading it. The issue is, the `wizarr/` subpath as defined in the location block is not included when Wizarr responds. I had a look through the admin.py file and near as I can tell the APP_URL variable is only used during the invite creation process, the subpath is not parsed out into a variable that is then used anywhere.

It looks like the `return redirect("/subpath")` function is used for most of the application navigation and I suspect this is the root cause. I think what is happening is that the redirect is not aware of the subpath. I found this stackoverflow post that goes over some potential routes for fixing this:
https://stackoverflow.com/questions/67737069/how-to-host-a-flask-app-on-a-subfolder-url-prefix-with-nginx

**Comment by realashleybailey** [comment]
Yes, I think the docs are currently a little confusing, as I do not believe Wizarr currently supports subpaths only subdomains. Subpath support is entailed to be supported in V3 but we are a little off from release of V3 yet. Apologies for the inconvenience.

**Comment by downj05** [comment]
> > Hi
> > No i havent, and havent tried without an update since the issue is clearly not on my side
> 
> Right from I've seen, it looks like you've just made a typo in the APP_URL environment variable :)

HOLY CRUD this fixed my issue im amazed someone made the same mistake as me drone eat more pie x
