### ISSUE TITLE
Feature: Password policy

### ISSUE THREAD

**Issue by M47kus** [Wizarrrr/wizarr#200]
There where options to define a password policy via env variables. Could you please add them back or better provide a settings page for it?

**Comment by realashleybailey** [comment]
V2 still has them there however the docs have been removed for them because it was confusing for some people, The same is true for V3 you can set the password policy using these variable:

MIN_PASSWORD_LENGTH
MIN_PASSWORD_UPPERCASE
MIN_PASSWORD_NUMBERS
MIN_PASSWORD_SPECIAL

we encourage people to use the defaults though because of security concerns.

**Comment by M47kus** [comment]
I have them set, but they don't work. I can easily use a password like "test" with setting a min length of 12

**Comment by realashleybailey** [comment]
Is this on V3
