### ISSUE TITLE
Cannot proceed after 'Join & Download Plex for this device' screen

### ISSUE THREAD

**Issue by Shedlow** [Wizarrrr/wizarr#246]
![Screenshot 2023-10-11 112605](https://github.com/Wizarrrr/wizarr/assets/98717149/b32912c8-582f-42f6-b885-0d299e40cd5f)

Hi, I cannot proceed once this screen comes up, it correctly pushes users to my domain and to plex.

Below is the error that follows once this screen finishes loading.

```
11:15:15 INFO 127.0.0.1 - - [2023-10-11 11:15:15] "GET /api/invitations/TEST23/verify HTTP/1.0" 200 277 0.002304
11:15:22 INFO 127.0.0.1 - - [2023-10-11 11:15:22] "POST /api/plex HTTP/1.0" 200 313 0.925011
/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'discord.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
  ```

**Comment by Shedlow** [comment]
Hi,

Even after resolving the Unverified HTTPS request being made to discord.com I still cannot proceed past this screen.

The console is showing no errors,
Neither is the logs.

I am on wizarr:v3-beta-3.4.2
Running on Unraid 6.12.3 under NGINX reverse proxy and cloudflare

**Comment by realashleybailey** [comment]
This isnt a bug, the WIzard was shortened because rewrote everything when doing V3, we are woking on Discord Widget screens and other screens for the Wizard in an upcoming update, please this isn't just directed at you but more so anybody coming across this post, stop comparing V2 to V3, they are both completely different softwares, rewritten from the ground up, so you can see why things in V2 may not be in V3 and things in V3 may not of been in V2.
