### ISSUE TITLE
Apple App Store / Google Play Store links dead

### ISSUE THREAD

**Issue by PierrePetit** [Wizarrrr/wizarr#290]
Hey !
Thanks a lot for this great tool. It makes me gain so much time when inviting people.

I noticed the links to the Apple App Store & Google Play Store are dead. 
In DownloadAppStore.vue, DownloadAndroid.vue & DownloadLinux.vue, the RouterLink component cannot take users to external urls, it needs to be an "a" tag :
```html
<a :href="to" target="_blank">
```
instead of
```html
<RouterLink :to="to">
```

Furthermore, the links take you to the **webpage** of the store, not the actual store itself.
I think you can use :
```vue.js
<DownloadAppStore to="itms-apps://geo.itunes.apple.com/developer/swiftfin/id1604098728" />
```
and
```vue.js
<DownloadAndroid to="market://details?id=dev.jdtech.jellyfin" />
```
in Download.vue.
I tested the Android one, but I don't have an apple device to test the App store one. If anyone reads this and has an apple device, it would be nice if you could test this link and say if this link works, and indicate which iOS version you have :
itms-apps://geo.itunes.apple.com/developer/swiftfin/id1604098728

Thanks again for your work 🚀

**Comment by PierrePetit** [comment]
I also realized there is a mistake in the french translation in  :
wizarr-frontend/src/language/fr/app.po

Two times, the word "sachez" is used and the correct word is "sachiez".

**Comment by realashleybailey** [comment]
Yes we use Weblate to allow the public to change language strings, but I’ll make sure to fix that, appreciate you sharing 🙂On Nov 4, 2023, at 5:11 PM, Pierre Petit ***@***.***> wrote:﻿
I also realized there is a mistake in the french translation in  :
wizarr-frontend/src/language/fr/app.po
Two times, the word "sachez" is used and the correct word is "sachiez".

**Comment by realashleybailey** [comment]
Ahh that’s so strange I will have our dev team look at this as soon as possible thank youOn Nov 4, 2023, at 4:59 PM, Pierre Petit ***@***.***> wrote:﻿
Hey !
Thanks a lot for this great tool. It makes me gain so much time when inviting people.
I noticed the links to the Apple App Store & Google Play Store are dead.
In DownloadAppStore.vue, DownloadAndroid.vue & DownloadLinux.vue, the RouterLink component cannot take users to external urls, it needs to be an "a" tag :
<a :href="to" target="_blank">
instead of
<RouterLink :to="to">
Furthermore, the links take you to the webpage of the store, not the actual store itself.
I think you can use :
<DownloadAppStore to="itms-apps://geo.itunes.apple.com/developer/swiftfin/id1604098728" />
and
<DownloadAndroid to="market://details?id=dev.jdtech.jellyfin" />
in Download.vue.
I tested the Android one, but I don't have an apple device to test the App store one. If anyone reads this and has an apple device, it would be nice if you could test this link and say if this link works, and indicate which iOS version you have :
itms-apps://geo.itunes.apple.com/developer/swiftfin/id1604098728
Thanks again for your work 🚀

**Comment by realashleybailey** [comment]
Fixed in beta, will be in the next production release
