### ISSUE TITLE
Support custom locations (reverse proxy paths)

### ISSUE THREAD

**Issue by qriff** [Wizarrrr/wizarr#79]
Is reverse proxy custom locations, i.e. paths support missing? (i.e. base URL)

(relatable reference) https://docs.ombi.app/settings/customization/#application-url-format

The Getting Started Reverse Proxy guide https://docs.wizarr.dev/getting-started/reverse-proxy isn't referring to custom paths
Nor does the Installation guide sample a feature complete APP_URL variable example, including a port and custom path in https://docs.wizarr.dev/getting-started/installation
https://en.wikipedia.org/wiki/URL

Whatever Nginx Proxy Manager custom path configurations and APP_URL combinations I try they all produce 404 errros in the app (obviously a multitude of others, like Ombi works without issues).

Example:
Works: https://wizarr.domain.com
Doesn't work: https://my.domain.com/wizarr/
Targets: https://192.168.1.1:5690
Baseurl would be: /wizarr

Only supporting subdomains presents a multitude of challenges especially in relation to certificate transparency (i.e. private urls) and other proxy efficiency aspects https://en.wikipedia.org/wiki/Certificate_Transparency
i.e.
https://crt.sh/

**Comment by mtthidoteu** [comment]
There is nothing that would prevent Wizarr working on anything that is possible with reverse proxy, the service is exposed at 0.0.0.0:5690 in the docker container and that's about it. 
Perhaps the docs are lacking in terms of path endpoints, but there is nothing that stops wizarr from working with that setup, it sounds more like a configration issue on your Reverse Proxy.

If you hop on to the discord server, I believe someone has already mentioned this :) https://discord.gg/SFbRKwxy

**Comment by D4rk56** [comment]
Same :/

`
		# -- Wizarr --
		location /wizarr {
                	proxy_pass http://172.18.0.1:5690;

	}
`

**Comment by spiritualized** [comment]
@mtthidoteu Wizarr cannot work properly on a prefix behind a reverse proxy without explicit support. If the application isn't aware that it is available on a prefix, then relative endpoints and static assets will be incorrectly served as if they exist on the domain root.

It is possible to look for each endpoint and manually map them through on the reverse proxy, like so...
```
    location ~ ^(/join|/j|/setup|/static) {
        proxy_pass http://wizarr:5690;
    }
```
however, this is a hack. If any endpoints on the app are added/edited, each existing user will have to edit their reverse proxy configuration, every time. The reverse proxy configuration should be unaware of Wizarr's implementation and specific endpoints.

In scenarios where a user needs a web application to run in a prefix, typically more than one web application is running on the same domain. Since Wizarr's static assets are located in /static, this means it's impossible to run any other web application alongside it, if it also has a /static folder (and almost all do).

Please consider adding this feature. A quick and easy implementation could take the prefix from an environment variable - then it could easily be passed into the docker container.

**Comment by spiritualized** [comment]
I figured out a way to get wizarr running with a URL prefix. It's possible to use nginx to rewrite HTML coming out of wizarr, and rewrite URL requests coming back in before they are passed to the app. This is still a hack, but it'll coexist alongside other applications on URL prefixes under the same domain. I'll try to keep the following gist updated if any routes are added/modified:

https://gist.github.com/spiritualized/c87fc97148e279b4c59c6fb51c1a7050

**Comment by ecapuano** [comment]
Curious why this was closed? The hacks above are not workable for all. App needs true base URL support IMHO. Otherwise, solutions like tailscale funnel will not work, because it will not rewrite URLs.
