### ISSUE TITLE
Feature Request: API for wizarr

### ISSUE THREAD

**Issue by tuxx** [Wizarrrr/wizarr#84]
Would be great if wizarr would expose an API so that we can create invites through api requests.

Probably not high up on the wishlist, but would be a nice feature imo.

I might look into this if i have the time.

**Comment by 8321876218** [comment]
Wizarr is already interacting with Plex API by utilizing [Python-PlexAPI](https://github.com/pkkid/python-plexapi). If you're already comfortable interacting with APIs I would recommend you check that out instead and adapt Wizarr to your own needs rather than requesting an API interacting for an API interaction.

**Comment by mtthidoteu** [comment]
This is definitely planned!

**Comment by mtthidoteu** [comment]
> Wizarr is already interacting with Plex API by utilizing [Python-PlexAPI](https://github.com/pkkid/python-plexapi). If you're already comfortable interacting with APIs I would recommend you check that out instead and adapt Wizarr to your own needs rather than requesting an API interacting for an API interaction.

Understandable, but then you can make use of the expiring invitations etc, and have everything in one place (I am integrating more user management feature)

**Comment by rahulkalluri** [comment]
Yeah, for example it'd be great to have a widget on [Homepage](https://github.com/benphelps/homepage) that shows requests open, closed, etc.
